version: '3.9'

services:
  app:
    build: .
    volumes:
      - ./:/app
    env_file: .env
    restart: "no"

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./:/app
    restart: unless-stopped
